version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run dev
          background: true
      - run:
          command: npm run dev:setup
      - run:
          command: npm run test-local
workflows:
  build-and-test:
    jobs:
      - build-and-test
