version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '10.19.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test:ci
workflows:
    build-and-test:
      jobs:
        - build-and-test
